from pathlib import Path
p=Path('index.html');s=p.read_text();s=s.replace('DOMINION UPDATE · V0.10','REVENANT UPDATE · V0.11').replace('23','46').replace('15 POWERS','24 POWERS').replace('15-power','24-power').replace('15 unique','24 unique').replace('15 powers','24 powers').replace('Twenty-three ways','Forty-six ways').replace('ALL 20','ALL 40').replace('ALL 23','ALL 46')
s=s.replace('BRUTAL <b>5</b>','BRUTAL <b>10</b>').replace('PYRO <b>6</b>','PYRO <b>12</b>').replace('PSYCHIC <b>5</b>','PSYCHIC <b>10</b>').replace('SPECTRAL <b>4</b>','SPECTRAL <b>8</b>').replace('BOSS <b>3</b>','BOSS <b>6</b>')
s=s.replace('<div id="resonanceHUD">','<div id="stanceHUD"><strong id="stanceName">REAVER</strong><span id="flowPips">◇◇◇</span><small id="flowHint">Z · STANCE / CONTACT CANCEL</small></div><div id="resonanceHUD">')
s=s.replace('<div class="codex-moves">','''<div class="codex-moves"><div><kbd>Z</kbd><span>Three combat stances<small>Reaver: quick claws and launchers. Breaker: heavier damage, will pressure and Marrow Crusher. Wraith: spectral Veil Rend. Switch just after contact for an 8-wrath recovery cancel and Flow.</small></span></div><div><kbd>F AFTER HIT</kbd><span>Guard Cancel<small>After your strike connects, spend 6 wrath to cancel recovery into parry. Cannot cancel before contact.</small></span></div><div><kbd>AIR HIT → SPACE</kbd><span>Enemy Step<small>Cancel an aerial hit to re-open the juggle. Costs 8 wrath, at most twice before the foe lands.</small></span></div><div><kbd>N</kbd><span>Flow Reversal<small>Perfect defense, precise links, guard breaks and stance cancels build three Flow pips. Spend all three on a protected area counter. Pips expire after seven seconds without a gain.</small></span></div>''')
p.write_text(s)
p=Path('src/main.js');s=p.read_text().replace('ALL 20','ALL 40').replace('ALL 23','ALL 46').replace('all 23','all 46').replace('all 20','all 40').replace('20 STANDARD','40 STANDARD').replace('3 BOSS EXECUTIONS','6 BOSS EXECUTIONS').replace('/ 23 EXECUTIONS','/ 46 EXECUTIONS')
s=s.replace('const sphereG=', 'const sphereG=')
s=s.replace('new THREE.SphereGeometry(1,12,10)','new THREE.SphereGeometry(1,20,16)').replace('new THREE.LatheGeometry(points,12)','new THREE.LatheGeometry(points,18)').replace('r1,r2,material,n=7','r1,r2,material,n=10')
s=s.replace("const skin=mat(isPlayer?'#552d29':elite?'#4e443e':'#424944',.8,.16)","const skin=mat(isPlayer?'#6b302a':elite?'#514650':'#4a5650',.66,.06)")
# A shared local, procedural surface texture (not downloaded art).
i=s.index('function creature(isPlayer=false')
s=s[:i]+'''const skinCanvas=document.createElement('canvas');skinCanvas.width=skinCanvas.height=128;const sk=skinCanvas.getContext('2d');sk.fillStyle='#b5afa7';sk.fillRect(0,0,128,128);for(let y=0;y<128;y+=4)for(let x=0;x<128;x+=4){const v=120+Math.floor((Math.sin(x*17+y*29)*.5+.5)*85);sk.fillStyle=`rgb(${v},${v},${v})`;sk.beginPath();sk.ellipse(x+(y%8?2:0),y,2,1.5,.2,0,TAU);sk.fill();}const skinTexture=new THREE.CanvasTexture(skinCanvas);skinTexture.wrapS=skinTexture.wrapT=THREE.RepeatWrapping;skinTexture.repeat.set(3,3);
'''+s[i:]
s=s.replace("const hips=new THREE.Group();hips.position.y=1.22;", "skin.bumpMap=skinTexture;skin.bumpScale=.032;skin.roughnessMap=skinTexture;flesh.bumpMap=skinTexture;flesh.bumpScale=.02;const hips=new THREE.Group();hips.position.y=1.22;")
# Replace faceted single shoulder with layered rounded caps.
s=s.replace("const pauldron=mesh(new THREE.IcosahedronGeometry(.28,0),plated,arms[i],side*.07,.015,-.005,1.45,.7,1.2);", "const pauldron=mesh(new THREE.SphereGeometry(.27,16,10,0,TAU,0,Math.PI*.65),plated,arms[i],side*.07,.015,-.005,1.3,.75,1.12);for(let layer=0;layer<2;layer++){const shell=mesh(new THREE.SphereGeometry(.25-layer*.025,14,8,0,TAU,0,Math.PI*.48),plated,arms[i],side*(.08+layer*.035),-.1-layer*.09,-.015,1.2,.5,1.08);shell.rotation.z=side*.25;}")
s=s.replace("return jaw;\n}","""for(let side of [-1,1]){const ridge=mesh(new THREE.TorusGeometry(.175,.018,5,18,Math.PI*.8),trim,head,side*.08,.22,.16);ridge.rotation.z=side*.3;for(let j=0;j<3;j++){const scar=box(torso,glow,side*(.28+j*.027),.46-j*.022,.285,.014,.1,.009);scar.rotation.z=side*.5;}}
 return jaw;
}""")
p.write_text(s)
p=Path('dominion.css');s=p.read_text()+'''\n#stanceHUD{position:absolute;left:32px;bottom:217px;display:flex;gap:12px;align-items:center;flex-wrap:wrap;max-width:300px;color:#e0c297}#stanceHUD strong{font:14px Georgia,serif;letter-spacing:2px}#flowPips{color:#b7e4d4;letter-spacing:5px}#flowHint{font:8px monospace;letter-spacing:1px;flex-basis:100%;color:#b9c4b7}.cinematic #stanceHUD{display:none}#wheelSvg .wheel-node path{stroke-width:1.2}#wheelSvg .wheel-node text{font-size:7px}.execution-filters{flex-wrap:wrap}\n''';p.write_text(s)
