from pathlib import Path
p=Path('index.html');s=p.read_text().replace('<link rel="stylesheet" href="/overhaul.css">','<link rel="stylesheet" href="/overhaul.css"><link rel="stylesheet" href="/finishers.css">')
s=s.replace('REQUIEM UPDATE · V0.3','GRIMOIRE UPDATE · V0.4')
s=s.replace('<button id="menuControls">', '<button id="menuFinishers">20 FINISHERS <span>↗</span></button><button id="menuControls">')
s=s.replace('<button id="pauseSettings">', '<button id="pauseFinishers">FINISHERS <kbd>V</kbd></button><button id="pauseSettings">')
s=s.replace('<kbd>E</kbd><div>SOULBREAKER<small>EXECUTE NEARBY FOE</small></div>', '<kbd>E</kbd><div><span id="finisherName">SOULBREAKER</span><small id="finisherHint">EXECUTE NEARBY FOE</small></div>')
s=s.replace('<kbd>E</kbd> FINISHER</span>', '<kbd>E</kbd> FINISHER / V SELECT</span>')
s=s.replace('<div><kbd>M</kbd><span>Map & waypoints</span></div>', '<div><kbd>M</kbd><span>Map & waypoints</span></div><div><kbd>V</kbd><span>20-finisher grimoire</span></div><div><kbd>O</kbd><span>Graphics & audio settings</span></div>')
s=s.replace('<div id="cinema"><div></div><div><span>SOULBREAKER</span></div></div>', '''<div id="finisherGrimoire" class="hidden screen-overlay"><div class="grimoire-wrap"><div class="panel-head"><div><small>THE EXECUTION GRIMOIRE</small><h2>Twenty ways to end a soul.</h2></div><button id="closeGrimoire" class="close-panel" aria-label="Close finisher grimoire">×</button></div><div class="grimoire-toolbar"><span id="equippedExecutionLabel">EQUIPPED: CYCLE ALL 20 · NO REPEATS</span><button id="cycleExecutions" class="cycle-executions active" aria-pressed="true"><span>↻</span> CYCLE ALL 20</button></div><div class="grimoire-layout"><section class="execution-library"><nav class="execution-filters" aria-label="Finisher schools"><button data-finisher-filter="all" class="active">ALL <b>20</b></button><button data-finisher-filter="brutal">BRUTAL <b>5</b></button><button data-finisher-filter="fire">PYRO <b>6</b></button><button data-finisher-filter="mind">PSYCHIC <b>5</b></button><button data-finisher-filter="ghost">SPECTRAL <b>4</b></button></nav><div id="executionList"></div><footer><span id="catalogVisibleCount">20 / 20 EXECUTIONS</span><span>ALL UNLOCKED · ALL BOSS-COMPATIBLE</span></footer></section><aside id="executionDetail"><div class="execution-insignia"><div id="catalogGlyph"></div><span id="catalogDuration">3.1 SECONDS</span></div><small id="catalogSchool">BRUTAL / EXECUTION 01</small><h3 id="catalogName">Soulbreaker</h3><p id="catalogDescription"></p><ol id="catalogBeats"></ol><p id="catalogSignature" class="execution-signature"></p><button id="equipExecution" class="primary"><span>EQUIP ON E</span><span>↗</span></button><button id="previewExecution" class="preview-execution"><span>▷</span> PLAY 3D PREVIEW</button><label class="boss-preview"><input id="bossPreview" type="checkbox"> BOSS-SIZE PREVIEW</label></aside></div><div class="grimoire-footer"><span><kbd>E</kbd> EXECUTE A WEAKENED OR WILL-BROKEN ENEMY <i>·</i> BOSSES REQUIRE 20% VITALITY</span><span><kbd>V</kbd> CLOSE GRIMOIRE</span></div></div></div>
<div id="cinema"><div><small id="previewNotice"></small></div><div><section class="execution-caption"><small id="executionSchool">BRUTAL / 01</small><span id="executionTitle">SOULBREAKER</span><small id="executionBeat">01 / CHEST STRIKE</small><div class="execution-progress-track"><i id="executionProgress"></i></div></section></div></div>''')
p.write_text(s)
