from pathlib import Path
p=Path('index.html');s=p.read_text().replace('<link rel="stylesheet" href="/style.css">','<link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/overhaul.css">')
s=s.replace('<button id="help"', '<button id="mapButton" class="icon-button" title="World map (M)">MAP <span>M</span></button><button id="settingsButton" class="icon-button" title="Settings"><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4"><path d="m10 2-1 3-3 1-3-1-2 4 2 2v3l-2 2 2 4 3-1 3 1 1 3h4l1-3 3-1 3 1 2-4-2-2v-3l2-2-2-4-3 1-3-1-1-3Z"/><circle cx="12" cy="12" r="3"/></svg></button><button id="help"')
s=s.replace('A PLAYABLE DARK FANTASY','REQUIEM UPDATE · V0.3')
s=s.replace('<span class="edition">CHAPTER I <i> / </i> THE AWAKENING</span>','<span class="edition" id="recordSummary">FOUR REALMS <i> / </i> ONE EXILE</span>')
s=s.replace('<div id="imbuement"></div>', '''<div id="imbuement"></div><div id="ascensionHUD"><div><small>ASCENSION</small><span><kbd>B</kbd> <b id="ascensionText">0%</b></span></div><div class="ascension-track"><i id="ascensionFill"></i></div><small id="boonCount">NO BLESSINGS CLAIMED</small></div><div id="radarHUD"><canvas id="radar" width="260" height="260"></canvas><small><kbd>M</kbd> OPEN REALM MAP</small></div><div id="bossHUD" class="hidden"><small id="bossPhase">KEEPER OF THE ASH</small><h3 id="bossName">VORATH, THE CINDER KING</h3><div><i id="bossFill"></i></div></div>''')
s=s.replace('<div id="cinema">', '''<div id="boonScreen" class="hidden screen-overlay"><div class="boon-wrap"><div class="eyebrow">THE HUNT HAS FED YOU</div><h2>Claim your damnation.</h2><p>Choose one blessing. Its power endures for the rest of this hunt.</p><div id="boonCards"></div><div class="boon-footer"><span id="boonWave">WAVE CLEARED</span><span>CHOOSE WITH <kbd>1</kbd> <kbd>2</kbd> <kbd>3</kbd> OR CLICK</span></div></div></div>
<div id="realmMap" class="hidden screen-overlay"><div class="map-wrap"><div class="panel-head"><div><small>THE FORSAKEN REALMS</small><h2>The world beyond the ash.</h2></div><button id="closeMap" class="close-panel" aria-label="Close map">×</button></div><div class="map-layout"><div class="map-chart"><canvas id="mapCanvas" width="850" height="690"></canvas><div class="map-legend"><span><i class="you-dot"></i> YOU</span><span><i class="foe-dot"></i> THE HUNT</span><span><i class="shrine-dot"></i> SHRINE</span></div></div><aside><small>MARK YOUR DESTINATION</small><div id="districtButtons"></div><div class="map-note"><span>SOUL COMMUNION</span><p>Each outer district holds a shrine. Approach and press <kbd>G</kbd> to restore vitality and wrath, once per wave.</p></div><button id="clearWaypoint" class="text-button">CLEAR WAYPOINT</button></aside></div><div class="map-bottom">FREE EXPLORATION <span>THE HUNT FOLLOWS YOU BETWEEN DISTRICTS</span> <kbd>M</kbd> CLOSE</div></div></div>
<div id="settingsPanel" class="hidden screen-overlay"><div class="settings-wrap"><div class="panel-head"><div><small>SHAPE YOUR EXPERIENCE</small><h2>In your hands.</h2></div><button id="closeSettings" class="close-panel" aria-label="Close settings">×</button></div><div class="setting-row"><div><strong>Rendering quality</strong><small>Low disables bloom and shadows.</small></div><select id="qualitySelect"><option value="low">Performance</option><option value="balanced">Balanced</option><option value="high">Cinematic</option></select></div><div class="setting-row"><div><strong>Look sensitivity</strong><small>Mouse camera rotation</small></div><input id="sensitivitySlider" aria-label="Mouse sensitivity" type="range" min="0.3" max="2" value="1" step="0.1"></div><div class="setting-row"><div><strong>Master volume</strong><small>Atmosphere and combat effects</small></div><input id="volumeSlider" aria-label="Master volume" type="range" min="0" max="1" value="0.6" step="0.05"></div><div class="setting-row"><div><strong>Impact camera shake</strong><small>Disable for a steadier camera.</small></div><input id="shakeToggle" aria-label="Impact camera shake" type="checkbox" checked></div><div class="setting-row"><div><strong>Full-screen hit flashes</strong><small>Disable to reduce intensity.</small></div><input id="flashToggle" aria-label="Full-screen hit flashes" type="checkbox" checked></div><p class="settings-note">Preferences and best-run records are saved in this browser. Current runs are not saved.</p><button id="settingsDone" class="primary"><span>RETURN TO THE ABYSS</span><span>↗</span></button></div></div>
<div id="cinema">''')
s=s.replace('<div><kbd>ESC</kbd><span>Pause / release cursor</span></div>', '<div><kbd>ESC</kbd><span>Pause / release cursor</span></div><div><kbd>B</kbd><span>Ascension ultimate</span></div><div><kbd>M</kbd><span>Map & waypoints</span></div>')
s=s.replace('Heavy blows break enemy will, opening an execution even above 60% health.', 'Heavy blows break enemy will, opening an execution even above 60% health. Bosses must be below 20%. Psychic attacks detonate burning enemies; spectral attacks reap broken souls.')
p.write_text(s)
