import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {FINISHERS} from '../src/finishers.js';
const src=fs.readFileSync('src/main.js','utf8'),ctx=vm.createContext({FINISHERS,options:{finisher:'auto',bossFinisher:'auto'},executionBag:[],bossExecutionBag:[],completedExecutions:[],rand:Math.random});vm.runInContext(src.slice(src.indexOf('function nextExecution('),src.indexOf('function startExecution(')),ctx);let prev;
for(let cycle=0;cycle<20;cycle++){const ids=[];for(let i=0;i<3;i++){const peek=vm.runInContext('nextExecution(false,true).id',ctx),id=vm.runInContext('nextExecution(true,true).id',ctx);assert.equal(peek,id);assert.notEqual(prev,id);ids.push(id);prev=id;ctx.completedExecutions.push(id);const normal=vm.runInContext('nextExecution(true,false).id',ctx);assert.ok(!FINISHERS.find(d=>d.id===normal).bossOnly);ctx.completedExecutions.push(normal);}assert.equal(new Set(ids).size,3);}console.log('60 boss + 60 normal interleaved selections, independent bags, no repeats PASS');
const b=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']}),p=await b.newPage({viewport:{width:1100,height:760}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{if(!localStorage.getItem('hellbound-settings'))localStorage.setItem('hellbound-settings',JSON.stringify({quality:'low'}));});await p.goto('http://localhost:5174/?test');await p.waitForFunction(()=>window.__hellbound?.testing);await p.evaluate(()=>{window.__hellbound.renderer.render=()=>{};window.requestAnimationFrame=()=>0});await p.waitForTimeout(100);
for(const d of FINISHERS.filter(d=>d.bossOnly)){
 await p.evaluate(()=>document.getElementById('start').click());await p.keyboard.press('v');await p.locator('[data-finisher-filter="boss"]').click();assert.equal(await p.locator('.execution-row').count(),3);await p.locator(`[data-execution="${d.id}"]`).click();assert.equal(await p.locator('#catalogBeats li').count(),6);assert.ok(await p.locator('#bossPreview').isDisabled());await p.click('#equipExecution');assert.equal(await p.evaluate(()=>window.__hellbound.state.bossFinisher),d.id);await p.keyboard.press('Escape');
 const old=await p.evaluate(()=>{const g=window.__hellbound,t=g.testing;t.setWave(3);t.restore();t.position(0,10);let idx=0;g.state.foes.forEach((e,i)=>{t.placeFoe(i,45+i,45);if(e.boss)idx=i;});t.placeFoe(idx,0,7);t.damage(idx,g.state.foes[idx].hp*.85);return g.state.score;});await p.keyboard.press('e');assert.equal(await p.evaluate(()=>window.__hellbound.state.execution?.id),d.id);await p.evaluate(n=>window.__hellbound.testing.advanceExecution(n),d.duration+.9);const s=await p.evaluate(()=>window.__hellbound.state);assert.equal(s.score-old,1195);assert.equal(s.foes.filter(e=>e.boss).length,0);assert.equal(s.completedExecutions.at(-1),d.id);console.log('Native E boss equip, six beats, kill/reward PASS',d.name);
}
await p.reload();await p.waitForFunction(()=>window.__hellbound?.testing);assert.equal(await p.evaluate(()=>window.__hellbound.state.bossFinisher),'sovereigns-ruin');console.log('Boss preference persistence PASS');await b.close();assert.equal(errors.length,0);
