import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const b=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});const p=await b.newPage({viewport:{width:960,height:640}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.addInitScript(()=>localStorage.setItem('hellbound-settings',JSON.stringify({quality:'low',gore:true})));await p.goto('http://localhost:5174/?test');await p.waitForFunction(()=>window.__hellbound?.testing?.executionSnapshot);await p.evaluate(()=>{window.savedRender=window.__hellbound.renderer.render;window.__hellbound.renderer.render=()=>{};window.requestAnimationFrame=()=>0});await p.waitForTimeout(100);
const defs=await p.evaluate(()=>window.__hellbound.testing.executionCatalog()),bosses=defs.filter(d=>d.bossOnly);assert.equal(defs.length,23);assert.equal(bosses.length,3);const results=[];
for(const def of [defs.find(d=>d.id==='cinder-spiral'),...bosses]){
 const result=await p.evaluate(def=>{const g=window.__hellbound,t=g.testing,old=g.state;t.preview(def.id,def.bossOnly);const frames=[];let goreMax=0;for(let i=0;i<Math.ceil(def.duration*60)+2;i++){t.advanceExecution(1/60);const s=t.executionSnapshot();if(s)frames.push(s);goreMax=Math.max(goreMax,g.state.gore.parts);}return {frames,goreMax,restored:JSON.stringify(old.player)===JSON.stringify(g.state.player),sameScore:old.score===g.state.score,partsAfter:g.state.gore.parts,ended:!g.state.finisher};},def);
 assert.ok(result.ended&&result.restored&&result.sameScore);assert.equal(result.partsAfter,0,'Preview gore ownership cleanup');const grips=result.frames.flatMap(f=>f.grips).filter(g=>g.weight>.99),drag=grips.filter(g=>g.type==='ankle-grip');if(drag.length){const error=Math.max(...drag.map(g=>g.error));assert.ok(drag.length>40,'Sustained grip, not a single contact pose');assert.ok(error<.05,`Ankle contact error ${error}`);console.log('SUSTAINED GRIP PASS',def.name,{frames:drag.length,error});}
 assert.ok(result.frames.flatMap(f=>f.joints.flat()).every(Number.isFinite));if(def.bossOnly)assert.ok(result.goreMax>=1,'Boss execution includes a severed part when gore is on');results.push({name:def.name,grips:grips.length,maxContact:Math.max(...grips.map(g=>g.error),0),goreMax:result.goreMax});console.log('NEW EXECUTION PASS',def.name);
}
async function reset(){await p.mouse.move(450,300);await p.evaluate(()=>{document.getElementById('start').click();const t=window.__hellbound.testing;t.setWave(1);t.restore();t.position(0,10.4);window.__hellbound.state.foes.forEach((_,i)=>t.placeFoe(i,40+i,40));t.placeFoe(0,0,8.1);t.toughFoe();t.combatReady();});await p.keyboard.press('Tab');}
async function clickHeavy(){await p.mouse.down({button:'right'});await p.mouse.up({button:'right'});}
await reset();await p.keyboard.down('a');await clickHeavy();await p.keyboard.up('a');assert.equal(await p.evaluate(()=>window.__hellbound.state.action),'sweep');await p.evaluate(()=>window.__hellbound.testing.advanceCombat(.55));assert.ok(await p.evaluate(()=>window.__hellbound.state.foes[0].downed>0));assert.ok(await p.evaluate(()=>window.__hellbound.state.physics.bodies>0));await p.evaluate(()=>window.__hellbound.testing.advanceCombat(.45));await clickHeavy();assert.equal(await p.evaluate(()=>window.__hellbound.state.action),'groundstrike');await p.evaluate(()=>window.__hellbound.testing.advanceCombat(2.6));assert.equal(await p.evaluate(()=>window.__hellbound.state.foes[0].recovering),false);console.log('Native directional sweep, live ragdoll, ground stomp and get-up PASS');
await reset();await p.keyboard.down('a');await clickHeavy();await p.keyboard.up('a');await p.evaluate(()=>window.__hellbound.testing.advanceCombat(.55));let burned=await p.evaluate(()=>{const g=window.__hellbound;g.testing.burn(0);return g.state.foes[0].hp;});await p.evaluate(()=>window.__hellbound.testing.advanceCombat(.2));assert.ok(await p.evaluate(hp=>window.__hellbound.state.foes[0].hp<hp,burned));await p.evaluate(()=>window.__hellbound.testing.breakWill(0));await p.keyboard.press('e');assert.ok(await p.evaluate(()=>window.__hellbound.state.finisher));await p.evaluate(()=>window.__hellbound.testing.advanceExecution(4.5));assert.equal(await p.evaluate(()=>window.__hellbound.state.finisher),false);console.log('Burn ticks through knockdown and native E can finish a downed target PASS');
await reset();await p.keyboard.down('s');await clickHeavy();await p.keyboard.up('s');assert.equal(await p.evaluate(()=>window.__hellbound.state.action),'hook');await p.evaluate(()=>window.__hellbound.testing.advanceCombat(.9));assert.ok(await p.evaluate(()=>window.__hellbound.state.clinchTime>0));await clickHeavy();assert.equal(await p.evaluate(()=>window.__hellbound.state.action),'knee');console.log('Native hook-to-knee branch PASS');
await reset();await p.keyboard.down('f');await p.evaluate(()=>window.__hellbound.testing.advanceCombat(.8));assert.equal(await p.evaluate(()=>window.__hellbound.state.action),'guard');await p.evaluate(()=>window.__hellbound.testing.hitGuard(20));let s=await p.evaluate(()=>window.__hellbound.state);assert.equal(s.health,97);assert.equal(s.energy,89);await p.keyboard.up('f');await p.evaluate(()=>window.__hellbound.testing.advanceCombat(.05));assert.equal(await p.evaluate(()=>window.__hellbound.state.action),null);console.log('Held guard, chip damage, wrath cost and release PASS');
await reset();await p.mouse.click(450,300);await p.evaluate(()=>window.__hellbound.testing.advanceCombat(.26));await p.mouse.click(450,300);await p.evaluate(()=>window.__hellbound.testing.advanceCombat(.25));assert.equal(await p.evaluate(()=>window.__hellbound.state.precise),true);console.log('Native contact-window perfect link PASS');
for(const d of bosses){await p.evaluate(id=>{const g=window.__hellbound;document.getElementById('start').click();g.testing.setWave(3);g.testing.restore();g.testing.executeVariant(id,true);},d.id);await p.evaluate(n=>window.__hellbound.testing.advanceExecution(n),d.duration+.9);s=await p.evaluate(()=>window.__hellbound.state);assert.equal(s.foes.filter(e=>e.boss).length,0);assert.equal(s.completedExecutions.at(-1),d.id);assert.ok(s.gore.parts>0);console.log('LIVE BOSS EXECUTION PASS',d.name);}
await p.keyboard.press('o');await p.locator('#goreToggle').uncheck();assert.equal(await p.evaluate(()=>window.__hellbound.state.gore.parts),0);assert.equal(await p.evaluate(()=>window.__hellbound.state.gore.stains),0);await p.click('#settingsDone');await reset();await p.evaluate(()=>window.__hellbound.testing.damage(0,9999,null));s=await p.evaluate(()=>window.__hellbound.state);assert.equal(s.gore.enabled,false);assert.equal(s.gore.drops,0);console.log('Gore toggle clears existing effects and disables new gore PASS');
fs.mkdirSync('.cache',{recursive:true});fs.writeFileSync('tests/carnage-results.json',JSON.stringify({results,errors},null,2));console.log('ERRORS',errors);await b.close();assert.equal(errors.length,0);
