import {chromium} from '@playwright/test';
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1000,height:700}});let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto((process.env.GAME_URL||'http://localhost:5174'));await page.waitForFunction(()=>window.__hellbound);await page.evaluate(()=>{window.savedRender=window.__hellbound.renderer.render;window.__hellbound.renderer.render=()=>{}});await page.click('#start');await page.waitForTimeout(3000);console.log('wave',await page.evaluate(()=>window.__hellbound.state));
await page.keyboard.down('r');await page.waitForTimeout(200);await page.locator('.wheel-slice[data-index="8"]').dispatchEvent('mouseenter');await page.evaluate(()=>document.querySelectorAll('#wheelSvg>g')[8].dispatchEvent(new MouseEvent('mouseenter')));await page.keyboard.up('r');await page.waitForTimeout(100);console.log('power',await page.evaluate(()=>window.__hellbound.state.selectedPower));await page.keyboard.press('q');await page.waitForTimeout(3200);console.log('gravity',await page.evaluate(()=>window.__hellbound.state));
// Test every spell via the actual UI and key bindings, while maintaining enough time for regeneration.
for(let i=0;i<15;i++){await page.keyboard.down('r');await page.evaluate(i=>document.querySelectorAll('#wheelSvg>g')[i].dispatchEvent(new MouseEvent('mouseenter')),i);await page.keyboard.up('r');await page.keyboard.press('q');await page.waitForTimeout(500);}
console.log('all spells attempted',await page.evaluate(()=>window.__hellbound.state));
await page.keyboard.press('Escape');await page.click('#restart');await page.waitForTimeout(10500);
await page.mouse.click(500,350);await page.waitForTimeout(500);await page.mouse.click(500,350);await page.waitForTimeout(700);console.log('after strikes',await page.evaluate(()=>window.__hellbound.state));await page.keyboard.press('e');await page.waitForTimeout(700);console.log('execution in progress',await page.evaluate(()=>window.__hellbound.state.finisher));await page.evaluate(()=>{window.__hellbound.renderer.render=window.savedRender;});await page.screenshot({path:'/home/user/combat.png'});await page.evaluate(()=>{window.__hellbound.renderer.render=()=>{}});await page.waitForTimeout(4000);console.log('after execution',await page.evaluate(()=>window.__hellbound.state));console.log('ERRORS',errors);await browser.close();
