import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs';
const b=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']}),p=await b.newPage({viewport:{width:900,height:650}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
try{await p.addInitScript(()=>localStorage.setItem('hellbound-settings',JSON.stringify({quality:'low'})));await p.goto('http://localhost:5174/?test');await p.waitForFunction(()=>window.__hellbound?.testing);await p.evaluate(()=>{__hellbound.renderer.render=()=>{};window.requestAnimationFrame=()=>0;});await p.waitForTimeout(100);
const defs=await p.evaluate(()=>__hellbound.testing.executionCatalog());const cases=[];for(const d of defs)cases.push({id:d.id,boss:!!d.bossOnly,x:0,z:8,angle:(cases.length%8)*Math.PI/4,distance:2+(cases.length%3)*1.4});
for(const id of ['soulbreaker','cinder-spiral','grave-driver','infernal-pillar','kingbreaker','sovereigns-ruin'])for(let a=0;a<8;a++)cases.push({id,boss:['kingbreaker','sovereigns-ruin'].includes(id),x:18,z:5,angle:a*Math.PI/4,distance:3.4});
let accepted=0,rejected=0,relocated=0,maxGap=0,maxStep=0,maxContact=0;const results=[];
for(const c of cases){await p.evaluate(c=>__hellbound.testing.arrangeExecution(c.id,c.boss,c.x,c.z,c.angle,c.distance),c);await p.keyboard.press('e');const before=await p.evaluate(()=>__hellbound.state);
 if(!before.finisher){assert.equal(before.executeCooldown,0);rejected++;results.push({...c,accepted:false});continue;}
 accepted++;assert.equal(before.execution.id,c.id);assert.ok(await p.evaluate(()=>__hellbound.testing.stagingValid()));if(before.staging.relocation||before.staging.rotation)relocated++;
 const result=await p.evaluate(()=>{const t=__hellbound.testing,st=__hellbound.state.staging;let maxGap=0,maxStep=0,maxContact=0,prev=__hellbound.state.player;for(let i=0;i<Math.ceil(st.duration*60);i++){t.advanceExecution(1/60);const now=__hellbound.state.player;maxStep=Math.max(maxStep,Math.hypot(now.x-prev.x,now.z-prev.z));prev=now;}const s=__hellbound.state;maxGap=Math.hypot(s.player.x-st.actorEntry[0],s.player.z-st.actorEntry[2]);for(let i=0;i<Math.ceil(s.execution.duration*60)+3;i++){t.advanceExecution(1/60);const snap=t.executionSnapshot();if(snap)for(const grip of snap.grips)if(grip.weight>.99)maxContact=Math.max(maxContact,grip.error);}return {maxGap,maxStep,maxContact,finished:!__hellbound.state.finisher,completed:__hellbound.state.completedExecutions.at(-1)};});assert.ok(result.finished);assert.equal(result.completed,c.id);assert.ok(result.maxGap<.01,JSON.stringify({c,result}));assert.ok(result.maxStep<.35);assert.ok(result.maxContact<.2,JSON.stringify({c,result}));maxGap=Math.max(maxGap,result.maxGap);maxStep=Math.max(maxStep,result.maxStep);maxContact=Math.max(maxContact,result.maxContact);results.push({...c,accepted:true,...result});}
// Impossible stage: victim is inside an obstacle. No reward/cooldown/teleport.
const o=await p.evaluate(()=>__hellbound.testing.obstacles()[0]);await p.evaluate(o=>__hellbound.testing.arrangeExecution('soulbreaker',false,o.x,o.z,0,3),o);const before=await p.evaluate(()=>__hellbound.state);await p.keyboard.press('e');const after=await p.evaluate(()=>__hellbound.state);assert.equal(after.finisher,false);assert.equal(after.executeCooldown,0);assert.deepEqual(after.player,before.player);assert.equal(after.score,before.score);
assert.ok(accepted>=23);assert.ok(relocated>0);assert.deepEqual(errors,[]);const summary={cases:cases.length,accepted,rejected,relocated,maxGap,maxStep,maxContact,errors,results};fs.writeFileSync('tests/dominion-staging-results.json',JSON.stringify(summary,null,2));console.log({...summary,results:undefined});}finally{await b.close();}
