import{chromium}from'@playwright/test';import assert from'node:assert/strict';import fs from'node:fs';
const b=await chromium.launch({args:['--no-sandbox','--enable-unsafe-swiftshader']}),p=await b.newPage({viewport:{width:720,height:520}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const label=process.env.BASELINE?'before':'after';fs.mkdirSync(`.cache/kinetic-${label}`,{recursive:true});
try{await p.addInitScript(()=>localStorage.setItem('hellbound-settings','{"quality":"low"}'));await p.goto('http://localhost:5174/?test');await p.waitForFunction(()=>__hellbound?.testing);await p.evaluate(()=>{window.savedRender=__hellbound.renderer.render;__hellbound.renderer.render=()=>{};requestAnimationFrame=()=>0;});await p.waitForTimeout(100);
const specs=[{name:'idle',kind:'idle',speed:0},{name:'walk',kind:'walk',speed:2.2},{name:'jog',kind:'walk',speed:6},{name:'sprint',kind:'sprint',speed:8.8},{name:'strafe',kind:'strafe',speed:4.2},{name:'backward',kind:'walk',speed:-3.4},{name:'turn-stop',kind:'idle',speed:0}];
const results=[];
for(const spec of specs){const result=await p.evaluate(({spec,capture})=>{const t=__hellbound.testing;t.studioBegin();let prev=null,maxSlide=0,maxError=0,maxFootStep=0,minSole=100,contacts=0,pairs=0,finite=true,images=[],bodyY=[],phases=[],frames=[];
for(let i=0;i<240;i++){const time=i/60;let s={...spec};if(spec.name==='turn-stop'){s.kind=time<1?'walk':'idle';s.position=[0,.06,Math.min(time,1)*4];s.yaw=time>1.7?Math.PI*Math.min(1,(time-1.7)/.8):0;}
const f=t.studioSample(s,time,1/60);finite&&=f.pose.every(Number.isFinite);bodyY.push(f.pose[1]);phases.push(f.motion.phase);if(i>30)for(let j=0;j<2;j++){const foot=f.motion.feet[j],old=prev?.motion.feet[j];minSole=Math.min(minSole,foot.actual[1]-.156);if(old)maxFootStep=Math.max(maxFootStep,Math.hypot(...foot.actual.map((x,k)=>x-old.actual[k])));if(foot.planted&&foot.goal){contacts++;maxError=Math.max(maxError,Math.hypot(...foot.actual.map((x,k)=>x-foot.goal[k])));if(old?.planted&&old.goal&&Math.hypot(foot.goal[0]-old.goal[0],foot.goal[2]-old.goal[2])<.001){pairs++;maxSlide=Math.max(maxSlide,Math.hypot(foot.actual[0]-old.actual[0],foot.actual[2]-old.actual[2]));}}}if(capture&&[72,84,96,108].includes(i)){__hellbound.renderer.render=savedRender;images.push(t.studioFrame());__hellbound.renderer.render=()=>{};}prev=f;}
t.studioEnd();return{finite,maxSlide,maxError,maxFootStep,minSole,contacts,pairs,bodyRange:Math.max(...bodyY)-Math.min(...bodyY),cycles:(phases.at(-1)-phases[0])/(Math.PI*2),images};},{spec,capture:!!process.env.CAPTURE});result.images.forEach((image,i)=>fs.writeFileSync(`.cache/kinetic-${label}/${spec.name}-${i}.png`,Buffer.from(image.split(',')[1],'base64')));delete result.images;results.push({name:spec.name,...result});console.log(spec.name,result);}
fs.writeFileSync(`tests/kinetic-${label}-results.json`,JSON.stringify({results,errors},null,2));assert.equal(errors.length,0);assert.ok(results.every(r=>r.finite));if(!process.env.BASELINE){assert.ok(results.every(r=>r.maxSlide<.065),'planted foot slide');assert.ok(results.every(r=>r.maxError<.09),'ground reach');assert.ok(results.every(r=>r.minSole>-.06),'foot-floor clearance');assert.ok(results.every(r=>r.maxFootStep<.38),'foot transition continuity');}
}finally{await b.close();}
