import{chromium}from'@playwright/test';import assert from'node:assert/strict';import fs from'node:fs';
const b=await chromium.launch({args:['--no-sandbox','--enable-unsafe-swiftshader']}),p=await b.newPage({viewport:{width:800,height:600}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
try{await p.addInitScript(()=>localStorage.setItem('hellbound-settings','{"quality":"low"}'));await p.goto('http://localhost:5174/?test');await p.waitForFunction(()=>__hellbound?.testing);await p.evaluate(()=>{__hellbound.renderer.render=()=>{};requestAnimationFrame=()=>0;});await p.waitForTimeout(100);const step=async n=>p.evaluate(n=>__hellbound.testing.advanceCombat(n),n),state=()=>p.evaluate(()=>__hellbound.state),snap=()=>p.evaluate(()=>__hellbound.testing.ruinSnapshot());
await p.evaluate(()=>__hellbound.testing.startMode('training'));await p.keyboard.press('u');await p.keyboard.press('Tab');await p.mouse.click(400,350);await step(.26);const hit=await snap();assert.equal(hit.action.hit,true);assert.equal(hit.action.targets,1);const hp=hit.enemies[0].hp;await step(.08);assert.equal((await snap()).enemies[0].hp,hp);await step(.6);
await p.evaluate(()=>{__hellbound.testing.combatReady();__hellbound.testing.ruinRend(3);});await p.keyboard.press('u');await p.evaluate(()=>__hellbound.testing.ruinRend(3));await p.keyboard.press('Tab');await p.mouse.click(400,350,{button:'right'});await step(.7);assert.ok((await state()).combatLog.includes('REND RUPTURE'));assert.equal((await snap()).enemies[0].rend,0);
await p.evaluate(()=>__hellbound.testing.combatReady());await p.keyboard.down('f');await p.evaluate(()=>__hellbound.testing.ruinHit());assert.match(await p.locator('#actionName').innerText(),/PERFECT PARRY/);await p.keyboard.up('f');await step(.8);assert.ok((await state()).health>0);
await p.keyboard.press('k');assert.equal((await state()).foes.length,3);assert.equal((await state()).trainingAI,true);let maxReservations=0,seen=new Set();for(let i=0;i<50;i++){await step(.1);const s=await snap();maxReservations=Math.max(maxReservations,s.encounter.activeReservations);s.enemies.forEach(e=>seen.add(e.state));}assert.ok(maxReservations<=2);assert.ok(seen.has('windup')&&seen.has('strike'));
await p.keyboard.press('y');await p.evaluate(()=>__hellbound.testing.ruinBossSweep(true));await step(.1);assert.equal((await snap()).enemies[0].bossMove.kind,'reap');await step(1.2);assert.equal((await snap()).enemies[0].bossMove.stage,'strike');await step(1.2);assert.equal((await snap()).enemies[0].bossMove.stage,'recover');await step(1.25);
await p.keyboard.press('h');await p.keyboard.press('v');assert.equal(await p.locator('.execution-row').count(),49);await p.keyboard.press('v');await p.keyboard.down('r');assert.equal(await p.locator('.wheel-slice').count(),24);assert.match(await p.locator('#wheelCost').innerText(),/READY|RECOVERING|NEED/);await p.keyboard.up('r');assert.deepEqual(errors,[]);
const report={singleHitWindow:true,rendRupture:true,trainingParry:true,groupDrill:true,maxReservations,observedEnemyStates:[...seen],bossSweep:true,preservedExecutions:49,preservedPowers:24,errors};fs.writeFileSync('tests/ruin-runtime-results.json',JSON.stringify(report,null,2));console.log(report);
}finally{await b.close();}
