from pathlib import Path
p=Path('src/main.js');s=p.read_text()
def rep(a,b):
 global s
 assert a in s,a[:120]
 s=s.replace(a,b)
rep("import * as THREE from 'three';","import * as THREE from 'three';\nimport {dreadSurface,makeSmallFiend} from './dread-models.js';")
rep("bossFinisher:'auto',gore", "bossFinisher:'auto',smallFinisher:'auto',gore")
rep('let bossExecutionBag=[],executionBag=[]','let smallExecutionBag=[],bossExecutionBag=[],executionBag=[]')
rep('return{root,rig,hips,spine,torso,neck,head,jaw,arms,forearms,hands,legs,shins,feet,toes,fingers,tail,wings,ownedMaterials,baseHip:1.22,isPlayer};','const result={root,rig,hips,spine,torso,neck,head,jaw,arms,forearms,hands,legs,shins,feet,toes,fingers,tail,wings,ownedMaterials,baseHip:1.22,isPlayer};dreadSurface(result);return result;')
rep('e.bar=bar;adornEnemy(e);','e.bar=bar;adornEnemy(e);if(total>1&&!boss&&!elite&&i%4===1)makeSmallFiend(e);')
rep("function nextExecution(consume=false,boss=false){\n const pool=FINISHERS.filter(f=>!!f.bossOnly===boss),choice=boss?options.bossFinisher:options.finisher;", "const executionKey=d=>d?.bossOnly?'bossFinisher':d?.smallOnly?'smallFinisher':'finisher';\nconst matchesExecution=(d,filter)=>filter==='all'||(filter==='boss'?!!d.bossOnly:filter==='small'?!!d.smallOnly:!d.bossOnly&&!d.smallOnly&&d.school===filter);\nfunction nextExecution(consume=false,boss=false,small=false){\n const pool=FINISHERS.filter(f=>boss?f.bossOnly:small?f.smallOnly:!f.bossOnly&&!f.smallOnly),choice=boss?options.bossFinisher:small?options.smallFinisher:options.finisher;")
rep('let bag=boss?bossExecutionBag:executionBag;','let bag=boss?bossExecutionBag:small?smallExecutionBag:executionBag;')
rep("const first=boss?'kingbreaker':'soulbreaker'", "const first=boss?'kingbreaker':small?'grave-stamp':'soulbreaker'")
rep('if(boss)bossExecutionBag=bag;else executionBag=bag;','if(boss)bossExecutionBag=bag;else if(small)smallExecutionBag=bag;else executionBag=bag;')
rep('if(def.bossOnly&&!e.boss)return false;', 'if(!def||def.bossOnly&&!e.boss||!!def.smallOnly!==!!e.small)return false;')
rep('const bag=[...executionBag],bossBag=[...bossExecutionBag];if(!startExecution(e,nextExecution(true,!!e.boss))){executionBag=bag;bossExecutionBag=bossBag;}', 'const bag=[...executionBag],bossBag=[...bossExecutionBag],smallBag=[...smallExecutionBag];if(!startExecution(e,nextExecution(true,!!e.boss,!!e.small))){executionBag=bag;bossExecutionBag=bossBag;smallExecutionBag=smallBag;}')
rep('nextExecution(false,!!readyTarget?.boss)', 'nextExecution(false,!!readyTarget?.boss,!!readyTarget?.small)')
rep("matches=d=>catalogFilter==='all'||(catalogFilter==='boss'?d.bossOnly:!d.bossOnly&&d.school===catalogFilter)", 'matches=d=>matchesExecution(d,catalogFilter)')
rep("const match=d=>catalogFilter==='all'||(catalogFilter==='boss'?d.bossOnly:!d.bossOnly&&d.school===catalogFilter)", 'const match=d=>matchesExecution(d,catalogFilter)')
rep('(d.bossOnly?options.bossFinisher:options.finisher)', 'options[executionKey(d)]')
rep("d.bossOnly?'BOSS EXCLUSIVE':d.id", "d.bossOnly?'BOSS EXCLUSIVE':d.smallOnly?'MIDGET EXCLUSIVE':d.id")
rep("def.bossOnly?'BOSS EXCLUSIVE / ':family.label+' / '", "def.bossOnly?'BOSS EXCLUSIVE / ':def.smallOnly?'MIDGET EXCLUSIVE / ':family.label+' / '")
rep('const option=def.bossOnly?options.bossFinisher:options.finisher', 'const option=options[executionKey(def)]')
rep("def.bossOnly?'EQUIP FOR BOSSES':'EQUIP ON E'", "def.bossOnly?'EQUIP FOR BOSSES':def.smallOnly?'EQUIP FOR MIDGETS':'EQUIP ON E'")
rep("def.bossOnly?'CYCLE 6 BOSS EXECUTIONS':'CYCLE 40 STANDARD EXECUTIONS'", "def.bossOnly?'CYCLE 7 BOSS EXECUTIONS':def.smallOnly?'CYCLE 2 MIDGET EXECUTIONS':'CYCLE 40 STANDARD EXECUTIONS'")
rep("$('bossPreview').disabled=!!def.bossOnly;$('bossPreview').checked=!!def.bossOnly||catalogBossPreview;", "$('bossPreview').disabled=!!def.bossOnly||!!def.smallOnly;$('bossPreview').checked=!def.smallOnly&&(!!def.bossOnly||catalogBossPreview);")
rep("def.bossOnly?'BOSSES: ':'STANDARD: '", "def.bossOnly?'BOSSES: ':def.smallOnly?'MIDGETS: ':'STANDARD: '")
rep('const boss=catalogBossPreview||!!def.bossOnly,e=creature(false,boss);', 'const boss=!def.smallOnly&&(catalogBossPreview||!!def.bossOnly),e=creature(false,boss);')
rep("panelOpen=null;paused=true;$('finisherGrimoire').classList.add('hidden');startExecution(e,def,true);", "if(def.smallOnly)makeSmallFiend(e);panelOpen=null;paused=true;$('finisherGrimoire').classList.add('hidden');startExecution(e,def,true);")
rep("options[FINISHERS.find(d=>d.id===catalogFocus)?.bossOnly?'bossFinisher':'finisher']", "options[executionKey(FINISHERS.find(d=>d.id===catalogFocus))]")
rep("if(options.finisher!=='auto'&&!FINISHERS.some(d=>d.id===options.finisher))options.finisher='auto';", "for(const key of ['finisher','bossFinisher','smallFinisher'])if(options[key]!=='auto'&&!FINISHERS.some(d=>d.id===options[key]&&executionKey(d)===key))options[key]='auto';")
rep('function trainingSpawn(boss=false,sparring=false){','function trainingSpawn(boss=false,sparring=false,small=false){')
rep("wave=boss?3:1;spawnEnemy(0,1);const e=enemies.at(-1);e.root.position", "wave=boss?3:1;spawnEnemy(0,1);const e=enemies.at(-1);if(small)makeSmallFiend(e);e.root.position")
rep("notify(boss?'Boss target", "notify(small?'Midget Fiend · E to execute · V for its exclusive finishers':boss?'Boss target")
rep("$('trainingBoss').onclick=()=>trainingSpawn(true);", "$('trainingBoss').onclick=()=>trainingSpawn(true);$('trainingSmall').onclick=()=>trainingSpawn(false,false,true);")
rep("if(e.code==='KeyY')trainingSpawn(true);", "if(e.code==='KeyY')trainingSpawn(true);if(e.code==='KeyI')trainingSpawn(false,false,true);")
rep('T: revenant · Y: boss · H:', 'T: revenant · Y: boss · I: midget · H:')
# Short creature attack: low approach, sharper tell, quicker recovery; no human/dwarf rig.
rep("*(e.stalker?1.3:1);if(e.stagger", "*(e.small?1.45:e.stalker?1.3:1);if(e.stagger")
rep('(e.caster?13:2.15)', '(e.caster?13:e.small?1.55:2.15)')
rep('if(e.stalker&&dist>4&&dist<12)', 'if((e.stalker||e.small)&&dist>3&&dist<12)')
rep('e.timer=e.elite?.95:.82', 'e.timer=e.small?.60:e.elite?.95:.82')
rep('e.timer=e.elite?.85:1.2', 'e.timer=e.small?.65:e.elite?.85:1.2')
rep('hurt(e.elite?22:12,false,pos)', 'hurt(e.small?9:e.elite?22:12,false,pos)')
rep('if(sepLen<1.65&&sepLen>.001&&pos.y<1&&!finisher){pos.addScaledVector(separation.normalize(),1.65-sepLen);}', 'const bodySpace=e.small?1.15:1.65;if(sepLen<bodySpace&&sepLen>.001&&pos.y<1&&!finisher){pos.addScaledVector(separation.normalize(),bodySpace-sepLen);}')
# Avoid above-small-enemy slashes: scale attack visual height to actual stature.
rep('slash(pos.clone().add(new THREE.Vector3(0,1.5,0)),e.root.rotation.y', 'slash(pos.clone().add(new THREE.Vector3(0,e.small?.8:1.5,0)),e.root.rotation.y')
# Test the real selection, spawning and ownership paths.
rep("stagingValid(){", "dreadSelection(boss=false,small=false,count=10){return Array.from({length:count},()=>nextExecution(true,boss,small).id);},\n trainingSmall(){trainingSpawn(false,false,true);},\n goreEnabled(value){options.gore=value;},\n stagingValid(){")
rep('bossOnly:!!d.bossOnly,description:d.description', 'bossOnly:!!d.bossOnly,smallOnly:!!d.smallOnly,description:d.description')
rep('wavePending=false;spawnEnemy(0,1);const e=enemies[0];e.root.position', "wavePending=false;spawnEnemy(0,1);const e=enemies[0];if(FINISHERS.find(d=>d.id===id)?.smallOnly)makeSmallFiend(e);e.root.position")
rep("options[boss?'bossFinisher':'finisher']=id", "options[executionKey(FINISHERS.find(d=>d.id===id))]=id")
rep('id:f.def.id,actorLegAngles', 'id:f.def.id,small:!!f.enemy.small,events:[...f.events||[]],actorLegAngles')
rep('boss:!!e.boss,kind:e.kind', 'boss:!!e.boss,small:!!e.small,speed:e.speed,kind:e.kind')
s=s.replace('46 EXECUTIONS','49 EXECUTIONS').replace('VIEW ALL 46','VIEW ALL 49').replace('all 46 executions','all 49 executions')
s=s.replace("'#30221e',1.45", "'#211b1b',1.12").replace("'#d1c1a2',2.1", "'#b5c7ce',1.8").replace("'#eb632c',2.2", "'#bc593c',1.9")
p.write_text(s)
p=Path('src/finishers.js');s=p.read_text().replace("import * as THREE from 'three';", "import * as THREE from 'three';\nimport {DREAD_FINISHERS,dreadChoreography} from './dread-executions.js';").replace('...BOSS_FINISHERS,...NEW_EXECUTIONS]', '...BOSS_FINISHERS,...NEW_EXECUTIONS,...DREAD_FINISHERS]').replace('if(!d.expanded)d.duration','if(!d.expanded&&!d.bespoke)d.duration').replace('if(reworkExecution(f,u,', 'if(dreadChoreography(f,u,{player,at,contact,event}))return;\n  if(reworkExecution(f,u,');p.write_text(s)
p=Path('src/execution-impact.js');s=p.read_text().replace('if(STRIKE_ENDINGS.has(def.id))', 'if(Number.isFinite(def.release))return def.release;\n if(STRIKE_ENDINGS.has(def.id))');p.write_text(s)
p=Path('src/execution-timing.js');s=p.read_text().replace('const u=Math.min', 'if(def.bespoke)return Math.min(seconds,def.duration);\n const u=Math.min');p.write_text(s)
p=Path('src/locomotion.js');s=p.read_text().replace('lerp(1.15,1.65','lerp(1.18,1.78').replace('const feral=r.stalker?.8:0', 'const feral=r.small?1.3:r.stalker?.8:0').replace('load*.026*w', 'load*.040*w').replace('Math.cos(p-.12)*.035', 'Math.cos(p-.12)*.052').replace('Math.cos(p-.18)*.08', 'Math.cos(p-.18)*.115').replace('lerp(.23,.82,run)', 'lerp(.34,.78,run)').replace('prowl*(i?.08:.17)', 'prowl*(i?.04:.10)').replace(')*.052,', ')*.068,');p.write_text(s)
p=Path('index.html');s=p.read_text().replace('PREDATOR UPDATE · V0.14.0','DREAD UPDATE · V0.15.0').replace('Forty-six ways','Forty-nine ways').replace('46','49').replace('all 6 boss','all 7 boss');s=s.replace('<button id="trainingBoss">','<button id="trainingSmall">I · MIDGET</button><button id="trainingBoss">');s=s.replace('<button data-finisher-filter="boss">BOSS <span>6</span></button>', '<button data-finisher-filter="boss">BOSS <span>7</span></button><button data-finisher-filter="small">MIDGET <span>2</span></button>');p.write_text(s)
