from pathlib import Path
p=Path('src/main.js');s=p.read_text()
def rep(a,b):
 global s
 assert a in s,a[:100]
 s=s.replace(a,b,1)
rep('p=powers[powerIndex];if(cooldowns', 'p=powers[powerIndex],overcast=!!(keys.ShiftLeft||keys.ShiftRight),cost=p.cost*(elapsed-lastMeleeHit<.8?.75:1)*(overcast?1.35:1);if(cooldowns')
rep('if(energy<p.cost*(elapsed-lastMeleeHit<.8?.75:1))','if(energy<cost)')
rep('energy-=p.cost*(weave?.75:1);cooldowns[selected]=p.cd','energy-=cost;cooldowns[selected]=p.cd*(overcast?1.15:1)')
rep("duration:weave?.56:.85,school:p.type", "duration:overcast?(weave?.78:1.08):(weave?.56:.85),overcast,school:p.type")
rep("paid:p.cost*(weave?.75:1)","paid:cost")
rep("actionText(weave?'SPELLWEAVE · '+p.name.toUpperCase():p.name.toUpperCase());", "actionText((overcast?'OVERCAST · ':weave?'SPELLWEAVE · ':'')+p.name.toUpperCase());")
rep("if(weave)recordMove('SPELLWEAVE');origin.copy", "if(weave)recordMove('SPELLWEAVE');if(overcast){recordMove('OVERCAST');eclipseSystems?.styleHit('overcast-'+powerIndex,8);}origin.copy")
rep('projectile(hand,dir,colors.fire,43,26,null)','projectile(hand,dir,colors.fire,overcast?64:43,overcast?32:26,null)')
rep("j*.14);projectile(hand,d,colors.fire,33,18", "j*(overcast?.18:.14));projectile(hand,d,colors.fire,overcast?45:33,18")
rep("radius:6,duration:1.25,t:0,tick:0,color:colors.fire,target:point.clone()", "radius:overcast?8:6,power:overcast?1.4:1,duration:1.25,t:0,tick:0,color:colors.fire,target:point.clone()")
rep("type:'fireDash',t:0,duration:.5,dir", "type:'fireDash',overcast,t:0,duration:overcast?.7:.5,dir")
rep("makeZone(point,'vortex',5.5,5.5)","makeZone(point,'vortex',overcast?6.5:5.5,overcast?7:5.5,overcast?1.4:1)")
rep("hitArea(origin,11,85,15,5)", "hitArea(origin,overcast?13:11,overcast?115:85,overcast?19:15,overcast?7:5)")
rep("damageEnemy(e,60,5,0,null,'mind')", "damageEnemy(e,overcast?82:60,overcast?9:5,overcast&&e.broken>0?4:0,null,'mind')")
rep("target.tk=target.boss?0:1.15;", "target.tk=target.boss?0:1.15;target.tkHeight=overcast?4.2:2.7;target.tkForce=overcast?72:48;")
rep("makeZone(point,'gravity',7,5)","makeZone(point,'gravity',overcast?8.5:7,overcast?6.5:5,overcast?1.5:1)")
rep("hitArea(origin,9,46,3,0,'mind')", "hitArea(origin,overcast?11:9,overcast?64:46,overcast?7:3,0,'mind')")
rep("if(!e.dead&&flatDistance(e.root.position,origin)<9)e.stagger=3.5", "if(!e.dead&&flatDistance(e.root.position,origin)<(overcast?11:9)){e.stagger=overcast?4.5:3.5;if(overcast)e.broken=Math.max(e.broken||0,2.2);}")
rep("slowTime=6;makeZone(origin,'rift',11,6)", "slowTime=overcast?8:6;makeZone(origin,'rift',overcast?14:11,overcast?8:6)")
rep("case 11:for(let j=0;j<3;j++)", "case 11:for(let j=0;j<(overcast?5:3);j++)")
rep("(j-1)*.6,.3,0)),dir.clone().applyAxisAngle(vup,(j-1)*.35)","(j-(overcast?2:1))*.6,.3,0)),dir.clone().applyAxisAngle(vup,(j-(overcast?2:1))*.35)")
rep("case 12:ghostTime=4;invuln=4", "case 12:ghostTime=overcast?6:4;invuln=ghostTime")
rep("damageEnemy(e,42,0,0,null,'ghost')", "damageEnemy(e,overcast?58:42,0,0,null,'ghost')")
rep("health+n*13", "health+n*(overcast?18:13)")
rep("Object.assign(s,{life:9,timer:.4,phase:i})", "Object.assign(s,{life:overcast?12:9,power:overcast?1.4:1,timer:.4,phase:i})")
rep("function makeZone(pos,type,radius,duration)","function makeZone(pos,type,radius,duration,power=1)")
rep("zones.push({mesh:g,type,radius,duration,t:0,tick:0,color})", "zones.push({mesh:g,type,radius,duration,power,t:0,tick:0,color})")
rep("hitArea(z.target,6,105,14,7)", "hitArea(z.target,z.radius,105*(z.power||1),14*(z.power||1),7)")
rep("(z.type==='gravity'?17:11)/massOf(e)", "(z.type==='gravity'?17:11)*(z.power||1)/massOf(e)")
rep("damageEnemy(e,z.type==='gravity'?9:13,0,0", "damageEnemy(e,(z.type==='gravity'?9:13)*(z.power||1),0,0")
rep("damageEnemy(a.target,18,2,0,null,'ghost')", "damageEnemy(a.target,18*(s.power||1),2,0,null,'ghost')")
rep("damageEnemy(e,58,8);", "damageEnemy(e,a.overcast?78:58,a.overcast?12:8);")
rep("const target=2.7;e.vy+=", "const target=e.tkHeight||2.7;e.vy+=")
rep("e.vy=-17;e.slamPower=48;", "e.vy=-17;e.slamPower=e.tkForce||48;")
rep("get state(){return{physics:", "get state(){return{overcast:!!action?.overcast,physics:")
# A cast-phase readout, rather than relying on particles to communicate preparation.
rep("function updateNewHUD(){", "function updateNewHUD(){\n const casting=action?.type==='cast';$('castReadout').classList.toggle('hidden',!casting);if(casting){$('castReadout').textContent=(action.overcast?'OVERCAST · ':'')+(action.released?'RECOVERY':'GATHERING WRATH');$('castReadout').style.setProperty('--cast-progress',Math.min(100,action.t/(action.duration*action.releaseAt)*100)+'%');}\n")
p.write_text(s)
p=Path('src/motion.js');s=p.read_text();needle="if(attack?.type==='fireDash')";idx=s.index(needle);s=s[:idx]+"if(attack?.overcast){const load=hump(u,0,CAST_RELEASES[attack.powerIndex??0]);r.hips.position.y-=.17*load;r.spine.rotation.x-=.12*load;r.forearms.forEach(a=>a.rotation.x-=.25*load);}\n "+s[idx:];p.write_text(s)
p=Path('index.html');s=p.read_text().replace('<div><kbd>Q</kbd><span>Cast equipped power</span></div>', '<div><kbd>Q</kbd><span>Cast equipped power</span></div><div><kbd>SHIFT + Q</kbd><span>Overcast · 35% more wrath</span></div>');s=s.replace('<div class="codex-moves">','<div class="codex-moves"><div><kbd>SHIFT + Q</kbd><span>Overcast<small>Empower any of the 15 powers: stronger throws, wider fields, extra blades or longer summons. Costs 35% more wrath; longer windup and 15% longer cooldown.</small></span></div>');s=s.replace('<div class="combat-hints">','<div id="castReadout" class="hidden" aria-live="polite"></div><div class="combat-hints">');s=s.replace('<kbd>Q</kbd> CAST <b> / </b>','<kbd>Q</kbd> CAST <b> / </b><kbd>SHIFT Q</kbd> OVERCAST <b> / </b>');p.write_text(s)
p=Path('overhaul.css');s=p.read_text()+'''\n/* A readable windup/release cue for normal and empowered casting. */
#castReadout{position:fixed;left:50%;bottom:150px;transform:translateX(-50%);font:10px/1.8 system-ui,sans-serif;letter-spacing:.2em;color:#efd1aa;padding:7px 18px;background:rgba(12,17,19,.88);border:1px solid #645446;pointer-events:none;min-width:190px;text-align:center}
#castReadout:after{content:"";position:absolute;bottom:0;left:0;height:2px;width:var(--cast-progress,0%);background:#e5b780;box-shadow:0 0 7px #d77c43}.cinematic #castReadout{display:none}
''';p.write_text(s)
