from pathlib import Path
import json,datetime,shutil
p=Path('progress/status.json');s=json.loads(p.read_text());s['phase']='Review wave 2 — functional regressions passed; correcting visual clarity and capturing play evidence';s['updated']=datetime.datetime.now(datetime.timezone.utc).isoformat()
f='devil-may-cry-5-goliath-boss-fight-scree-1.jpg';shutil.copy('/home/user/image-search/'+f,'progress/references/'+f);s['references'][0].update(image='/references/'+f,url='https://gamewith.net/devil-may-cry-5/article/show/8239')
f='elden-ring-margit-boss-fight-hud-gamepla-1.jpg';shutil.copy('/home/user/image-search/'+f,'progress/references/'+f);s['references'][2].update(image='/references/'+f,url='https://www.gamesradar.com/elden-ring-margit-boss-how-to-beat-fell-omen/')
verified={'Active hit window':'Runtime: contact found in active interval; the same target was not damaged twice.','One hit per target per swing':'Unit tests + runtime health check.','Range and facing':'Unit-tested forward/behind/out-of-range and intervening obstacle cases.','Actual-contact cancels':'Three actual-contact stance cancels into Flow Reversal passed.','Parry practice':'Training now executes perfect-parry logic without player death.','Light-to-heavy payoff':'3 Rend marks consumed by heavy hit; Rupture recorded.','Concurrent attack budget':'10-actor simulation and running 3-actor drill remained at ≤2 attack reservations.','Attack-slot fairness':'All 10 eligible actors received reservations over the simulated fairness test.','Boss attack sequencing':'Runtime amber sweep entered windup, strike and recovery.','49 execution routing':'All 49 previews completed with a physical release.','Grip reach':'49 sampled previews: worst fully weighted residual 0.0567 world units; not a zero-contact-error claim.','Body spacing':'No measured core-proxy overlap in the 49-preview test; ornaments/limbs not certified.','24 spell release events':'All 24 native R-wheel/Q releases and persistent status effects passed.','Wheel affordability':'Runtime wheel exposes READY/NEED/RECOVERING state.','Wheel cooldown visibility':'State labels now reflect cooldown rather than only the static cooldown duration.','Training tools':'K drill creates three opponents and enables AI; I/Y/U retained.','Movement acceleration':'Native movement test passed: initial velocity bounded, target run speed reached.','Stopping distance':'Measured 0.2292 world units at tested normal run speed.','Reverse-direction response':'First reverse-turn frame limited to 0.1584 radians.','Dodge trajectory':'Native dodge/defense handling regression passed.','Browser exceptions':'No page errors in current functional suites.'}
for g in s['groups']:
 for i in g['items']:
  if i['name'] in verified:i.update(state='verified',note=verified[i['name']])
s['log'].append({'label':'VERIFICATION WAVE 1 · AUTOMATED, NOT AN AGENT','text':'Range/facing/deduplication and fair reservation tests passed. Runtime Rend, training parry, 3-enemy drill and boss sweep passed. 24 powers, native movement and 49 execution contact/timeline regressions passed.'})
s['log'].append({'label':'VISUAL REJECTION → REVISION','text':'Actual screenshots exposed overlapping tether/boon and realm/mode labels. Revised HUD row placement. Added a camera-side fill for silhouette visibility and an AI-generated, embedded basalt surface texture. Reference parity still rejected.'})
s['evidence'] +=[{'path':'/evidence/ruin-execution.png','title':'Wave 1: actual execution capture','note':'Closer visual inspection still shows procedural anatomy and a large remaining production-asset gap.'}]
p.write_text(json.dumps(s,indent=2))
