import * as THREE from 'three';
export function createGore(scene,enabled){
 const V=THREE.Vector3,dummy=new THREE.Object3D(),DROPS=220,STAINS=72,drops=new Array(DROPS),stains=new Array(STAINS),parts=[],severed=[];let cursor=0,mark=0;
 const spray=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,0),new THREE.MeshStandardMaterial({color:'#760d18',roughness:.46}),DROPS);spray.frustumCulled=false;spray.instanceMatrix.setUsage(THREE.DynamicDrawUsage);scene.add(spray);
 const pools=new THREE.InstancedMesh(new THREE.CircleGeometry(1,17),new THREE.MeshBasicMaterial({color:'#4b0711',transparent:true,opacity:.82,depthWrite:false}),STAINS);pools.frustumCulled=false;pools.instanceMatrix.setUsage(THREE.DynamicDrawUsage);scene.add(pools);
 function stain(pos,size,owner){stains[mark]={p:pos.clone().setY(.115),size,age:0,angle:mark*2.39,owner};mark=(mark+1)%STAINS;}
 function emit(pos,direction=new V(0,1,0),strength=1,owner=null){if(!enabled())return;const count=Math.min(56,Math.ceil(14*strength));for(let i=0;i<count;i++){const a=(cursor+i)*2.399,v=direction.clone().normalize().multiplyScalar(2+strength*1.6).add(new V(Math.cos(a)*2,1+(i%5)*.42,Math.sin(a)*2));drops[cursor]={p:pos.clone(),v,age:0,size:.022+(i%4)*.014,owner};cursor=(cursor+1)%DROPS;}stain(pos,.18+strength*.16,owner);}
 function disposePart(p){p.mesh.removeFromParent();p.mesh.traverse(n=>{n.geometry?.dispose();if(n.material){if(Array.isArray(n.material))n.material.forEach(m=>m.dispose());else n.material.dispose();}});}
 function sever(r,part='head',impulse=new V(0,4,1),owner=null){
  if(!enabled())return;const node=part==='head'?r.head:part==='arm0'?r.forearms[0]:part==='leg'?r.shins[1]:part==='leg0'?r.shins[0]:r.forearms[1];if(severed.some(s=>s.node===node))return;r.root.updateMatrixWorld(true);const clone=node.clone(true);clone.visible=true;clone.traverse(n=>{if(n.isMesh){n.geometry=n.geometry.clone();n.material=Array.isArray(n.material)?n.material.map(m=>m.clone()):n.material.clone();}});node.matrixWorld.decompose(clone.position,clone.quaternion,clone.scale);scene.add(clone);node.visible=false;
  const cap=new THREE.Mesh(new THREE.SphereGeometry(part==='head'?.14:part.startsWith('leg')?.13:.1,8,6),new THREE.MeshStandardMaterial({color:'#8f1620',roughness:.62}));cap.position.copy(node.position);cap.scale.set(1,.45,1);node.parent.add(cap);r.ownedMaterials?.add(cap.material);severed.push({node,cap,owner,root:r.root});parts.push({mesh:clone,v:impulse.clone(),spin:new V(2.1,-1.6,1.3),age:0,owner,radius:part==='head'?.22:part.startsWith('leg')?.16:.12});emit(clone.position,impulse,part==='head'?3.2:2.6,owner);
  while(parts.length>14)disposePart(parts.shift());
 }
 function clearOwner(owner){for(let i=0;i<drops.length;i++)if(drops[i]?.owner===owner)drops[i]=null;for(let i=0;i<stains.length;i++)if(stains[i]?.owner===owner)stains[i]=null;for(let i=parts.length-1;i>=0;i--)if(parts[i].owner===owner){disposePart(parts[i]);parts.splice(i,1);}for(let i=severed.length-1;i>=0;i--)if(severed[i].owner===owner){severed[i].node.visible=true;severed[i].cap.visible=false;severed.splice(i,1);}update(0);}
 function reset(){drops.fill(null);stains.fill(null);parts.splice(0).forEach(disposePart);severed.splice(0).forEach(s=>{s.node.visible=true;s.cap.visible=false;});update(0);}
 function update(dt){const on=enabled();spray.visible=pools.visible=on;for(let i=0;i<DROPS;i++){const d=drops[i];if(on&&d&&d.age<1.25){d.age+=dt;d.v.y-=18*dt;d.p.addScaledVector(d.v,dt);if(d.p.y<.12){if(d.age<1.2)stain(d.p,.06+(i%3)*.04,d.owner);d.age=1.3;}dummy.position.copy(d.p);dummy.rotation.set(d.age*5,i,d.age*3);dummy.scale.setScalar(d.age<1.25?d.size:0);}else dummy.scale.setScalar(0);dummy.updateMatrix();spray.setMatrixAt(i,dummy.matrix);}for(let i=0;i<STAINS;i++){const s=stains[i];if(on&&s&&s.age<50){s.age+=dt;dummy.position.copy(s.p);dummy.rotation.set(-Math.PI/2,0,s.angle);const size=s.size*Math.max(0,Math.min(1,(50-s.age)/6));dummy.scale.set(size,size*.62,1);}else dummy.scale.setScalar(0);dummy.updateMatrix();pools.setMatrixAt(i,dummy.matrix);}spray.instanceMatrix.needsUpdate=pools.instanceMatrix.needsUpdate=true;
  for(let i=parts.length-1;i>=0;i--){const p=parts[i];p.mesh.visible=on;p.age+=dt;p.v.y-=23*dt;p.mesh.position.addScaledVector(p.v,dt);if(p.mesh.position.y<p.radius){p.mesh.position.y=p.radius;p.v.y=Math.abs(p.v.y)*.2;p.v.x*=.86;p.v.z*=.86;p.spin.multiplyScalar(.84);}p.mesh.rotation.x+=p.spin.x*dt;p.mesh.rotation.y+=p.spin.y*dt;p.mesh.rotation.z+=p.spin.z*dt;if(p.age>6){disposePart(p);parts.splice(i,1);}}
 }
 function snapshot(){return {enabled:enabled(),drops:drops.filter(d=>d&&d.age<1.25).length,stains:stains.filter(s=>s&&s.age<50).length,parts:parts.length};}
 function release(r){for(let i=severed.length-1;i>=0;i--)if(severed[i].root===r.root)severed.splice(i,1);}
 reset();return {emit,sever,update,reset,clearOwner,release,snapshot,meshes:()=>[spray,pools,...parts.map(p=>p.mesh)]};
}
