import * as THREE from 'three';
// Bounded, reusable debris and floor scars. Architecture itself is not destructible.
export function createImpactWorld(scene){
 const capacity=64,scars=16,dummy=new THREE.Object3D(),chunks=[],marks=[];
 const debris=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,0),new THREE.MeshStandardMaterial({color:'#65574b',roughness:1}),capacity);debris.castShadow=true;debris.receiveShadow=true;debris.instanceMatrix.setUsage(THREE.DynamicDrawUsage);debris.frustumCulled=false;scene.add(debris);
 const stain=new THREE.InstancedMesh(new THREE.CircleGeometry(1,24),new THREE.MeshBasicMaterial({color:'#1e1714',transparent:true,opacity:.43,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1}),scars);stain.instanceMatrix.setUsage(THREE.DynamicDrawUsage);stain.frustumCulled=false;scene.add(stain);let cursor=0,mark=0;
 function reset(){chunks.length=0;marks.length=0;for(let i=0;i<capacity;i++){dummy.scale.setScalar(0);dummy.updateMatrix();debris.setMatrixAt(i,dummy.matrix);}for(let i=0;i<scars;i++)stain.setMatrixAt(i,dummy.matrix);debris.instanceMatrix.needsUpdate=stain.instanceMatrix.needsUpdate=true;}
 function strike(position,strength=1){const amount=Math.min(20,Math.round(9*strength));for(let i=0;i<amount;i++){const a=i/amount*Math.PI*2+.19*cursor,speed=(2.2+(i%4)*.8)*strength;chunks[cursor]={p:position.clone().setY(.18),v:new THREE.Vector3(Math.cos(a)*speed,3.4+(i%3)*1.2,Math.sin(a)*speed),age:0,size:.055+(i%4)*.028,spin:a,bounces:0};cursor=(cursor+1)%capacity;}marks[mark]={p:position.clone().setY(.11),age:0,r:Math.min(2.6,.85+strength*.65),angle:cursor};mark=(mark+1)%scars;}
 function update(dt){for(let i=0;i<capacity;i++){const c=chunks[i];if(c&&c.age<2.4){c.age+=dt;c.v.y-=23*dt;c.p.addScaledVector(c.v,dt);if(c.p.y<c.size){c.p.y=c.size;c.v.y=Math.abs(c.v.y)*.2;c.v.x*=.65;c.v.z*=.65;c.bounces++;}dummy.position.copy(c.p);dummy.rotation.set(c.age*4,c.spin+c.age*3,c.age*2);dummy.scale.setScalar(c.size*Math.max(0,Math.min(1,(2.4-c.age)*2)));}else dummy.scale.setScalar(0);dummy.updateMatrix();debris.setMatrixAt(i,dummy.matrix);}for(let i=0;i<scars;i++){const m=marks[i];if(m&&m.age<28){m.age+=dt;dummy.position.copy(m.p);dummy.rotation.set(-Math.PI/2,0,m.angle);dummy.scale.set(m.r,m.r*.68,1);dummy.scale.multiplyScalar(Math.max(0,Math.min(1,(28-m.age)/4)));}else dummy.scale.setScalar(0);dummy.updateMatrix();stain.setMatrixAt(i,dummy.matrix);}debris.instanceMatrix.needsUpdate=stain.instanceMatrix.needsUpdate=true;}
 reset();return {strike,update,reset};
}
